### PR TITLE
Update Lang.java

### PR DESCRIPTION
**Pull request by TreemanKing**
Adds Hex Colour Support.

https://www.spigotmc.org/threads/chatcolor-implementation-%C2%A7x-x.505831/

### CODE REVIEW

**Comment by sekwah41** [comment]
Just give me a ping when this is no longer a wip and ready! :)

**Comment by TreemanKing** [comment]
I was thinking we might want to end up using the Adventure API instead of this? The current method was implemented by Spigot in 1.16.
Any thoughts? @sekwah41

**Comment by sekwah41** [comment]
The recode is meant to abstract everything so we can have the same code almost running on forge and fabric.

**Comment by TreemanKing** [comment]
@sekwah41 did you want me to put this into the other PR or keep it here.

**Comment by sekwah41** [comment]
Keep it separate :) always good to keep things separate :D

**Review by sekwah41 — APPROVED** [review]

**Pull request merged**
