### PR TITLE
Even More Changes

### PR DESCRIPTION
**Pull request by Maxqia**
I tried to do reflection, but couldn't figure out how to get a class from a class :P, so I looked at and cherry-picked your commits. Can you from now on commit directly to master? You also probably should do a release, because a lot of bugs have been fixed recently.

### CODE REVIEW

**Comment by sekwah41** [comment]
Sure, ill merge your commits and do some testing and look over it for a release. Ill possibly do it later today.

**Comment by sekwah41** [comment]
desti was counted as a destination manager  and awarp was for warping to specific locations, thats my only issue.

**Comment by Maxqia** [comment]
I was going for something like essentials /warp commands

**Comment by Maxqia** [comment]
0_0 what the crap did you do to the git history

**Comment by sekwah41** [comment]
what do you mean? .-.

**Comment by sekwah41** [comment]
Also I commited and then found bugs one by one thinking they were the final things xD so i kinda spammed a few last night.

**Pull request merged**
