### PR TITLE
Remove `hasWarped` metadata when warped to bungee:

### PR DESCRIPTION
**Pull request by HarvelsX**
The server sends players faster than the plugin expects, with the properly configured proxy server.
The plugin should not rely on server delays.

Fixes https://github.com/sekwah41/Advanced-Portals/issues/329;

### CODE REVIEW

**Comment by MightyGoldenOctopus** [comment]
@sekwah41 Mind reviewing it now ? It is needed to fix the issue where vanilla portals become unusable after using an AdvancedPortal

**Comment by sekwah41** [comment]
To be clear, the plugin has never relied on server delays as the pr description suggests. It was due to some old issues with spigot which seemed to trigger the portal events after a player has been moved so it wasn't possible to check the initial move location.

This was likely due to the move event going through then the teleport triggering a new move so when in creative it would trigger instantly, move then fire the portal event too.

I am reviewing it right now, though from what I can see this is not a viable fix to the initial issue that it was created to solve.

While that initial issue may not exist anymore post 1.13, this would still be an invalid fix.

Logically this also both removes the metadata before the actual teleport as well as instantly removes it before anything else has happened in the event that a portal is actually triggered.





While this may fix it, logically this is no different to removing the metadata tag altogether.

**Comment by sekwah41** [comment]
@MightyGoldenOctopus can you specify the version of the plugin as well as spigot/paper or whatever is being used? I will try to re-create this and make a fix.

Ill continue the discussion over in #329

**Comment by sekwah41** [comment]
Ive implemented a variation of this, while the intentions of this PR are to fix a specific issue, they cause major issues for paper especially due to how certain events trigger causing the player to be teleported to the nether anyway.

Instead I've implemented (when its merged) the boolean  value being replaced by a timestamp to allow the events to ignore its existence if the removal event doesn't trigger or it gets bugged out.

**Pull request closed without merging**
