### PR TITLE
Various Changes

### PR DESCRIPTION
**Pull request by Maxqia**
...

### CODE REVIEW

**Comment by sekwah41** [comment]
Ill try and merge them as soon as possible and implement as many as i can in the rewrite :)

**Comment by Maxqia** [comment]
The thing is, that I can't merge into the portals-rewrite branch without reverting ~7 of your last commits, because they try to rewrite my code. Can you instead of rewriting my code, git cherry-pick my commits?

**Comment by sekwah41** [comment]
whats git cherry pick .-. Sorry im bad with terms. I know intellij has a merging tool tho.

**Comment by sekwah41** [comment]
Also I still need to rewrite a lot of the stuff and ive been working on some of my own stuff which yours added some of. So ill be doing a large merge at the end to make sure the stuff is sorted.

**Comment by sekwah41** [comment]
Fyi I am converting the craftbukkit sections to reflection, so craftbukkit will not be needed as one of the dependancies.

**Pull request merged**
