### PR TITLE
Added waro subcommand

### PR DESCRIPTION
**Pull request by FabioZumbi12**
Fixes:
- Null result on TAB commands.

Tweaks:
- Added `warp` subcommand to command `/portal`.

Reason: (Leave this if it is obvious why from the tweak and/or fix notes)

### CODE REVIEW

**Comment by sekwah41** [comment]
Did you mean to do this? It looks like the pull request is currently to the wrong branch of the git. I was originally confused why so much looked like it had changed xD

**Comment by sekwah41** [comment]
Oh sorry just saw the new request

**Comment by FabioZumbi12** [comment]
Yeah xD
I added warp subcommand to this version too, but i need to organize my workspace before create a pullrequest too.

This new version will be amazing the way you is making ;)

**Comment by sekwah41** [comment]
Thanks :) I was having to sort some details out for a part time job and year in industry but I'm back and live streaming a bunch of dev so it shouldn't be too long till its out :)

**Pull request closed without merging**
