### PR TITLE
feat: folia support

### PR DESCRIPTION
**Pull request by sekwah41**

### CODE REVIEW

**Comment by sekwah41** [comment]
Should be almost ready for  use.

**Comment by xcomcadx** [comment]
[18:29:45 ERROR]: Couldn't parse player advancements in ./world/advancements/00000000-0000-0000-0009-01f33c28d6a1.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1802 column 28 path $.minecraft:recipes/building_blocks/deepslate_tile_slab_from_deepslate_tiles_stonecutting
        at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar:?]
        at net.minecraft.server.PlayerAdvancements.load(PlayerAdvancements.java:133) ~[?:?]
        at net.minecraft.server.PlayerAdvancements.<init>(PlayerAdvancements.java:72) ~[?:?]
        at net.minecraft.server.players.PlayerList.getPlayerAdvancements(PlayerList.java:1597) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:404) ~[?:?]
        at net.craftersland.data.bridge.utils.nms.Version_1_20_R1.loadPlayer(Version_1_20_R1.java:136) ~[MysqlPlayerDataBridge-v4.9.2.jar:?]
        at net.craftersland.data.bridge.events.PlayerDisconnect$1.run(PlayerDisconnect.java:39) ~[MysqlPlayerDataBridge-v4.9.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.lambda$handle$8(CraftScheduler.java:594) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:310) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:165) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1802 column 28 path $.minecraft:recipes/building_blocks/deepslate_tile_slab_from_deepslate_tiles_stonecutting
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.nextName(JsonReader.java:796) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:783) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
        at com.google.gson.internal.Streams.parse(Streams.java:49) ~[gson-2.10.jar:?]
        ... 15 more

**Comment by sekwah41** [comment]
> [18:29:45 ERROR]: Couldn't parse player advancements in ./world/advancements/00000000-0000-0000-0009-01f33c28d6a1.json com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1802 column 28 path $.minecraft:recipes/building_blocks/deepslate_tile_slab_from_deepslate_tiles_stonecutting at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar:?] at net.minecraft.server.PlayerAdvancements.load(PlayerAdvancements.java:133) ~[?:?] at net.minecraft.server.PlayerAdvancements.(PlayerAdvancements.java:72) ~[?:?] at net.minecraft.server.players.PlayerList.getPlayerAdvancements(PlayerList.java:1597) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at net.minecraft.server.level.ServerPlayer.(ServerPlayer.java:404) ~[?:?] at net.craftersland.data.bridge.utils.nms.Version_1_20_R1.loadPlayer(Version_1_20_R1.java:136) ~[MysqlPlayerDataBridge-v4.9.2.jar:?] at net.craftersland.data.bridge.events.PlayerDisconnect$1.run(PlayerDisconnect.java:39) ~[MysqlPlayerDataBridge-v4.9.2.jar:?] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.lambda$handle$8(CraftScheduler.java:594) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.1.jar:?] at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.1.jar:?] at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:310) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:165) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1802 column 28 path $.minecraft:recipes/building_blocks/deepslate_tile_slab_from_deepslate_tiles_stonecutting at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?] at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042) ~[gson-2.10.jar:?] at com.google.gson.stream.JsonReader.nextName(JsonReader.java:796) ~[gson-2.10.jar:?] at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:783) ~[gson-2.10.jar:?] at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?] at com.google.gson.internal.Streams.parse(Streams.java:49) ~[gson-2.10.jar:?] ... 15 more

this doesnt look like its to do with my plugin at all.

**Comment by sekwah41** [comment]
As discussed on the issue, there are reasons this was abandoned at the time at least.https://github.com/sekwah41/Advanced-Portals/issues/375

**Comment by sekwah41** [comment]
Closing for now as this is on the old version of the plugin. Will revisit when folia is more complete.

**Pull request closed without merging**
